# Spring Boot configuration
spring:
  profiles:
    active: development
  # Database
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: "jdbc:mysql://j19-biblioteca.cb7rekoppnry.eu-west-1.rds.amazonaws.com:3306/biblio"
    username: biblio
    password: papapollo
  # JPA properties
  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    generate-ddl: true
# Logger configuration
logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
    org.springframework: info
    org.hibernate: info
# Server configuration
server:
  port: 8080 #set your port
